### ISSUE TITLE
Click confirmation

### ISSUE THREAD

**Issue by mp4096** [tum-rt/emoji-feedback#3]
Is being addressed in ddf21acb01ad31ee0ed8acfb7ffb89857d1dfc3c

@syxolk On my machine I get the "Thanks" message even if I'm button mashing and the server is returning error status. Is this still WIP?

**Comment by syxolk** [comment]
Fixed with commit 4db8eef2054f31468d3bc0d442610bf899d87bb9

**Comment by mp4096** [comment]
Closed in #5
