### ISSUE TITLE
Blurry thanks message

### ISSUE THREAD

**Issue by syxolk** [tum-rt/emoji-feedback#4]
![image](https://cloud.githubusercontent.com/assets/6666063/25850727/a22ed4ba-34c3-11e7-9290-0a7c443b17eb.png)

This does not work:

```
-webkit-font-smoothing: subpixel-antialiased;
```

**Comment by syxolk** [comment]
For unknown reasons this works: `transform: scale(10) translate(0, -30px);`, instead of `transform: scale(10) translate(0, -100%);`.

**Comment by mp4096** [comment]
:open_mouth: ok. Of course I prefer relative units, but hey...

**Comment by syxolk** [comment]
Also: We want [smooth as butter animations at 60 fps](https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108)

Conditions:
- :ballot_box_with_check: Never ever animate with javascript
- :ballot_box_with_check: Use CSS animations
- :ballot_box_with_check: Use CSS animations but restrict yourself to translate, scale, rotate and opacity

What we didn't have:
- Use `will-change` to promote an element to its own layer. Most browsers will do this on their own but you can help them with this attribute.

**Comment by syxolk** [comment]
Fixed with 52034e39bdf75bee62d7e85767e480f83ca2a161

**Comment by mp4096** [comment]
Wow, good job!

**Comment by mp4096** [comment]
Closed in #5
